/**
 * Company A' 54 authorized dealer brands.
 * Shared between /api/products/match (server) and Step3Product UI (client).
 */
export const OUR_DEALERS = {
  "Schurter":             { website: "https://www.schurter.com/en/products-and-solutions/catalog", products: "Fuses, Connectors, Switches, EMC products" },
  "SETfuse":              { website: "https://www.setfuse.com/",                                    products: "Over-Temperature / Voltage / Current Protection, Active Protection" },
  "Nanjing Electric":     { website: "https://www.ntcshiheng.com",                                  products: "NTC Thermistor, PTC Thermistor, Voltage Varistor, Temperature" },
  "Cooltron":             { website: "https://www.cooltron.com",                                    products: "AC & DC fans/blowers, EC Axial Fan" },
  "MEGA":                 { website: "https://cnmegatech.com",                                      products: "AC & DC Axial fan, AC & DC Blowers, EC Axial Fan" },
  "CDIL":                 { website: "https://www.cdil.com",                                        products: "Diodes, Transistors, Rectifiers, Regulators, MOSFET, TRIAC, SCR" },
  "Rectron":              { website: "https://www.rectron.com/",                                    products: "TVS Diode, Bridge Rectifier, ESD Diode, Schottky Diode, MOSFET" },
  "Diotec":               { website: "https://diotec.com/en/home.htm",                              products: "Schottky Diode, SiC Schottky, Zener, Transistor, MOSFET" },
  "SMC Diode Solutions":  { website: "https://www.smc-diodes.com/",                                 products: "Diodes, Rectifiers, MOSFET, ESD Protection, Thyristor" },
  "Goford Semiconductor": { website: "http://gofordsemi.com/",                                      products: "Trench MOSFET, Planar MOSFET, Multi-epi SJ MOSFET" },
  "NexGen Power":         { website: "https://www.nexgenpowersystems.com/",                         products: "IGBT, Super Junction MOSFET, SiC MOSFET" },
  "HY Group":             { website: "https://www.hygroup.com.tw/",                                 products: "Rectifier, Bridge Rectifier, TVS Diode, Zener Diode, MOSFET" },
  "UTC Unisonic":         { website: "https://en.unisonic.com.tw/",                                 products: "Power Management ICs, Transistors, MOSFET, IGBT, TRIAC, SCR, Diode" },
  "Knitter-Switch":       { website: "https://www.knitter-switch.com/eng",                          products: "Toggle, Pushbutton, Tact, Slide, Rotary Switches" },
  "Diptronics":           { website: "http://www.dip.com.tw/en/",                                   products: "DIP, TACT, Rotary, Slide Switches" },
  "Zhejiang Jinja":       { website: "http://www.jinjiaelc.com",                                    products: "USB-C, Phone jack, RJ45, USB, DC Power Jack" },
  "Greenconn":            { website: "https://www.greenconn.com/",                                  products: "Board-to-board, wire-to-board, I/O connectors" },
  "Anyconn":              { website: "https://www.anyconn.tw",                                      products: "Board-to-board, Terminal block, I/O connector" },
  "Amphenol":             { website: "https://www.amphenol-in.com",                                 products: "Board-to-Board, Circular, IC sockets, I/O connector" },
  "Degson":               { website: "https://www.degson.com",                                      products: "Terminal Blocks, Circular Connectors, Din-Rail TB" },
  "Phoenix Contact":      { website: "https://www.phoenixcontact.com",                              products: "PCB connectors, Terminal blocks, Cables" },
  "Antenk":               { website: "https://www.antenk.com",                                      products: "PCB Connectors, Battery holders, Pin Headers" },
  "KLS Electronic":       { website: "https://www.klsele.com",                                      products: "Switches, Connectors, Antennas, Ethernet" },
  "TE Connectivity":      { website: "https://www.te.com/en/home.html",                             products: "Connectors, Relays, Sensors, Cable, Antennas" },
  "Ze Ming Lang Xi":      { website: "https://www.micro-transformer.com/",                          products: "Current transformer" },
  "3L Coils":             { website: "https://www.3lcoils.com",                                     products: "Inductors, Power choke, Wireless charger coils" },
  "Coilmaster":           { website: "https://www.coilmaster.com.tw",                               products: "Automotive inductor, Power inductor" },
  "Jackcon":              { website: "https://www.jackcon.com.tw/",                                 products: "Aluminum Electrolytic, Ceramic, Film Capacitor" },
  "PSA":                  { website: "http://www.pdc.com.tw/",                                      products: "MLCC, Chip Resistor, Inductor" },
  "Hokuriku":             { website: "https://www.hdk.co.jp/english/index_e.htm",                   products: "Chip Resistor, NTC Thermistor, Resistor" },
  "Song Chuan":           { website: "https://songchuanusa.com/",                                   products: "Electromechanical Relays, Relay Sockets" },
  "Hongfa":               { website: "https://www.hongfa.com/",                                     products: "Relays, EV contactor, Current Sensors" },
  "Standex Electronics":  { website: "https://standexelectronics.com/",                             products: "Relays, Optocoupler, Reed Switches" },
  "GigaDevice":           { website: "https://www.gigadevice.com/",                                 products: "Flash Memory, 32-bit MCU, Power, Motor Drivers" },
  "Intelligent Memory":   { website: "https://www.intelligentmemory.com/",                          products: "DRAM, NAND Flash" },
  "Fudan Micro":          { website: "https://www.fm-chips.com/",                                   products: "EEPROM, SPI NOR/NAND Flash, Microcontroller" },
  "Netsol":               { website: "http://www.netsol.co.kr",                                     products: "STT-MRAM, Asynchronous SRAM" },
  "Megawin":              { website: "https://www.megawin.com",                                     products: "8051 & ARM Cortex-M0+ MCU" },
  "Weltrend":             { website: "http://www.weltrend.com",                                     products: "USB PD, MCU, Motor Driver, PMIC" },
  "CXW":                  { website: "https://www.cxwic.net/",                                      products: "USB PD, DC/DC Converter, PMIC" },
  "Silergy":              { website: "https://www.silergy.com/",                                    products: "Battery mgmt, DC-DC, AC-DC, Motor driver" },
  "Clafpower":            { website: "https://www.clafpower.com",                                   products: "DC-DC, AC-DC converters" },
  "SGMicro":              { website: "https://www.sg-micro.com",                                    products: "LDO, Amplifier, LED driver, Comparator" },
  "Novosens":             { website: "https://www.novosns.com/",                                    products: "CAN tx, Amplifiers, Gate Drivers, Pressure sensors" },
  "TDK (Micronas)":       { website: "https://www.micronas.tdk.com",                                products: "Hall Sensors, Angle sensor, Current Sensing ICs" },
  "Taimi":                { website: "https://www.uttransducer.com",                                products: "Ceramic Pressure, Ultrasonic sensor" },
  "Indie Semiconductor":  { website: "https://www.indiesemi.com",                                   products: "Wireless Charging, Lighting, ADAS" },
  "Socle Technology":     { website: "https://www.socle-tech.com",                                  products: "Wi-Fi & BLE Module, Sensor modules" },
  "Sonytek":              { website: "https://www.sonytek.com/",                                    products: "LCD, TFT Display, Touch Panel" },
  "DWIN":                 { website: "https://www.dwin-global.com/",                                products: "HMI LCD Modules, TFT LCD with RTP/CTP" },
  "Kingstate":            { website: "https://www.kingstate.com.tw/",                               products: "Piezo / Magnetic Buzzer, Speaker, Microphone" },
  "Seoul Semiconductor":  { website: "https://www.seoulsemicon.com",                                products: "Automotive & Indoor/Outdoor LEDs" },
  "Dapu":                 { website: "https://www.dptel.com",                                       products: "RTC, Ethernet PHY, Crystal Oscillator" },
  "Arduino":              { website: "https://www.arduino.cc/",                                     products: "Project Kits for Robotics" },
} as const;

export type DealerBrand = keyof typeof OUR_DEALERS;
export const DEALER_NAMES = Object.keys(OUR_DEALERS) as DealerBrand[];
